rounds_list = [
    { "round": 1, "enemies": [ { "type": "Red", "cant": 40 } ], "interval": 600 },
    { "round": 2, "enemies": [ { "type": "Red", "cant": 65 } ], "interval": 550 },
    { "round": 3, "enemies": [ { "type": "Blue", "cant": 30 } ], "interval": 500 },
    { "round": 4, "enemies": [ { "type": "Red", "cant": 40 }, { "type": "Blue", "cant": 20 } ], "interval": 500 },
    { "round": 5, "enemies": [ { "type": "Green", "cant": 25 } ], "interval": 450 },
    { "round": 6, "enemies": [ { "type": "Green", "cant": 25 }, { "type": "Blue", "cant": 20 } ], "interval": 450 },
    { "round": 7, "enemies": [ { "type": "Yellow", "cant": 30 } ], "interval": 400 },
    { "round": 8, "enemies": [ { "type": "Yellow", "cant": 25 }, { "type": "Green", "cant": 25 } ], "interval": 400 },
    { "round": 9, "enemies": [ { "type": "Pink", "cant": 30 } ], "interval": 350 },
    { "round": 10, "enemies": [ { "type": "Pink", "cant": 30 }, { "type": "Yellow", "cant": 20 } ], "interval": 350 },
    { "round": 11, "enemies": [ { "type": "Armored", "cant": 20 } ], "interval": 300 },
    { "round": 12, "enemies": [ { "type": "Armored", "cant": 20 }, { "type": "Pink", "cant": 20 } ], "interval": 300 },
    { "round": 13, "enemies": [ { "type": "Armored", "cant": 25 } ], "interval": 280 },
    { "round": 14, "enemies": [ { "type": "Armored", "cant": 25 }, { "type": "Pink", "cant": 15 } ], "interval": 270 },
    { "round": 15, "enemies": [ { "type": "Armored", "cant": 40 } ], "interval": 260 },
    { "round": 16, "enemies": [ { "type": "Pink", "cant": 50 }, { "type": "Yellow", "cant": 30 } ], "interval": 250 },
    { "round": 17, "enemies": [ { "type": "Armored", "cant": 20 }, { "type": "Pink", "cant": 50 } ], "interval": 240 },
    { "round": 18, "enemies": [ { "type": "Armored", "cant": 45 } ], "interval": 230 },
    { "round": 19, "enemies": [ { "type": "Pink", "cant": 45 }, { "type": "Yellow", "cant": 30 } ], "interval": 220 },
    { "round": 20, "enemies": [ { "type": "Armored", "cant": 45 }, { "type": "Pink", "cant": 30 } ], "interval": 210 },
    { "round": 21, "enemies": [ { "type": "Armored", "cant": 40 } ], "interval": 200 },
    { "round": 22, "enemies": [ { "type": "Pink", "cant": 50 }, { "type": "Armored", "cant": 15 } ], "interval": 190 },
    { "round": 23, "enemies": [ { "type": "Armored", "cant": 40 } ], "interval": 180 },
    { "round": 24, "enemies": [ { "type": "Pink", "cant": 60 }, { "type": "Armored", "cant": 20 } ], "interval": 170 },
    { "round": 25, "enemies": [ { "type": "Armored", "cant": 40 }, { "type": "Pink", "cant": 30 }, { "type": "Blue", "cant": 20 } ], "interval": 160 },
    { "round": 26, "enemies": [ { "type": "Pink", "cant": 90 }, { "type": "Armored", "cant": 15 }, { "type": "Yellow", "cant": 40 } ], "interval": 150 },
    { "round": 27, "enemies": [ { "type": "Armored", "cant": 50 }, { "type": "Blue", "cant": 35 }, { "type": "Green", "cant": 40 } ], "interval": 140 },
    { "round": 28, "enemies": [ { "type": "Pink", "cant": 100 }, { "type": "Armored", "cant": 30 }, { "type": "Yellow", "cant": 50 } ], "interval": 130 },
    { "round": 29, "enemies": [ { "type": "Armored", "cant": 60 }, { "type": "Blue", "cant": 50 }, { "type": "Green", "cant": 50 } ], "interval": 120 },
    { "round": 30, "enemies": [ { "type": "Pink", "cant": 110 }, { "type": "Armored", "cant": 40 }, { "type": "Yellow", "cant": 60 } ], "interval": 110 },
    { "round": 31, "enemies": [ { "type": "Armored", "cant": 70 }, { "type": "Blue", "cant": 60 }, { "type": "Green", "cant": 60 } ], "interval": 100 },
    { "round": 32, "enemies": [ { "type": "Pink", "cant": 120 }, { "type": "Armored", "cant": 50 }, { "type": "Yellow", "cant": 70 } ], "interval": 90 },
    { "round": 33, "enemies": [ { "type": "Armored", "cant": 80 }, { "type": "Blue", "cant": 70 }, { "type": "Green", "cant": 70 } ], "interval": 80 },
    { "round": 34, "enemies": [ { "type": "Pink", "cant": 140 }, { "type": "Armored", "cant": 60 }, { "type": "Yellow", "cant": 80 } ], "interval": 75 },
    { "round": 35, "enemies": [ { "type": "Armored", "cant": 90 }, { "type": "Blue", "cant": 80 }, { "type": "Green", "cant": 80 } ], "interval": 70 },
    { "round": 36, "enemies": [ { "type": "Pink", "cant": 160 }, { "type": "Armored", "cant": 70 }, { "type": "Yellow", "cant": 90 } ], "interval": 65 },
    { "round": 37, "enemies": [ { "type": "Armored", "cant": 100 }, { "type": "Blue", "cant": 90 }, { "type": "Green", "cant": 90 } ], "interval": 60 },
    { "round": 38, "enemies": [ { "type": "Pink", "cant": 170 }, { "type": "Armored", "cant": 80 }, { "type": "Yellow", "cant": 100 } ], "interval": 55 },
    { "round": 39, "enemies": [ { "type": "Armored", "cant": 110 }, { "type": "Blue", "cant": 100 }, { "type": "Green", "cant": 100 } ], "interval": 50 },
    { "round": 40, "enemies": [ { "type": "Pink", "cant": 180 }, { "type": "Armored", "cant": 90 }, { "type": "Yellow", "cant": 110 } ], "interval": 45 },
    { "round": 41, "enemies": [ { "type": "Armored", "cant": 100 }, { "type": "Pink", "cant": 150 }, { "type": "Green", "cant": 40 } ], "interval": 40 },
    { "round": 42, "enemies": [ { "type": "Armored", "cant": 110 }, { "type": "Pink", "cant": 160 }, { "type": "Green", "cant": 50 } ], "interval": 38 },
    { "round": 43, "enemies": [ { "type": "Armored", "cant": 120 }, { "type": "Pink", "cant": 170 }, { "type": "Green", "cant": 60 } ], "interval": 35 },
    { "round": 44, "enemies": [ { "type": "Armored", "cant": 130 }, { "type": "Pink", "cant": 180 }, { "type": "Green", "cant": 70 } ], "interval": 33 },
    { "round": 45, "enemies": [ { "type": "Armored", "cant": 140 }, { "type": "Pink", "cant": 190 }, { "type": "Green", "cant": 80 } ], "interval": 30 },
    { "round": 46, "enemies": [ { "type": "Armored", "cant": 150 }, { "type": "Pink", "cant": 200 }, { "type": "Green", "cant": 90 } ], "interval": 28 },
    { "round": 47, "enemies": [ { "type": "Armored", "cant": 160 }, { "type": "Pink", "cant": 210 }, { "type": "Green", "cant": 100 }, { "type": "Yellow", "cant": 40 } ], "interval": 26 },
    { "round": 48, "enemies": [ { "type": "Armored", "cant": 170 }, { "type": "Pink", "cant": 220 }, { "type": "Green", "cant": 110 }, { "type": "Yellow", "cant": 50 } ], "interval": 24 },
    { "round": 49, "enemies": [ { "type": "Armored", "cant": 180 }, { "type": "Pink", "cant": 230 }, { "type": "Green", "cant": 120 }, { "type": "Yellow", "cant": 60 } ], "interval": 22 },
    { "round": 50, "enemies": [ { "type": "Armored", "cant": 200 }, { "type": "Pink", "cant": 250 }, { "type": "Green", "cant": 130 }, { "type": "Yellow", "cant": 70 }, { "type": "Blue", "cant": 80 } ], "interval": 20 }
]

#Pruba para ver como se comporta la victoria
"""rounds_list = [
    { "round": i, "enemies": [ { "type": "Red", "cant": 1 } ], "interval": 100 }
    for i in range(1, 51)
]"""