rounds_list = [
    { "round": 1, "enemies": [ { "type": "Red", "cant": 20 } ], "interval": 800 },
    { "round": 2, "enemies": [ { "type": "Red", "cant": 35 } ], "interval": 750 },
    { "round": 3, "enemies": [ { "type": "Blue", "cant": 15 } ], "interval": 700 },
    { "round": 4, "enemies": [ { "type": "Red", "cant": 25 }, { "type": "Blue", "cant": 10 } ], "interval": 700 },
    { "round": 5, "enemies": [ { "type": "Green", "cant": 12 } ], "interval": 650 },
    { "round": 6, "enemies": [ { "type": "Green", "cant": 15 }, { "type": "Blue", "cant": 10 } ], "interval": 650 },
    { "round": 7, "enemies": [ { "type": "Yellow", "cant": 15 } ], "interval": 600 },
    { "round": 8, "enemies": [ { "type": "Yellow", "cant": 12 }, { "type": "Green", "cant": 12 } ], "interval": 600 },
    { "round": 9, "enemies": [ { "type": "Pink", "cant": 15 } ], "interval": 550 },
    { "round": 10, "enemies": [ { "type": "Pink", "cant": 15 }, { "type": "Yellow", "cant": 10 } ], "interval": 550 },
    { "round": 11, "enemies": [ { "type": "Armored", "cant": 8 } ], "interval": 500 },
    { "round": 12, "enemies": [ { "type": "Armored", "cant": 10 }, { "type": "Pink", "cant": 10 } ], "interval": 500 },
    { "round": 13, "enemies": [ { "type": "Armored", "cant": 12 } ], "interval": 480 },
    { "round": 14, "enemies": [ { "type": "Armored", "cant": 12 }, { "type": "Pink", "cant": 8 } ], "interval": 470 },
    { "round": 15, "enemies": [ { "type": "Armored", "cant": 18 } ], "interval": 460 },
    { "round": 16, "enemies": [ { "type": "Pink", "cant": 25 }, { "type": "Yellow", "cant": 15 } ], "interval": 450 },
    { "round": 17, "enemies": [ { "type": "Armored", "cant": 10 }, { "type": "Pink", "cant": 25 } ], "interval": 440 },
    { "round": 18, "enemies": [ { "type": "Armored", "cant": 22 } ], "interval": 430 },
    { "round": 19, "enemies": [ { "type": "Pink", "cant": 22 }, { "type": "Yellow", "cant": 15 } ], "interval": 420 },
    { "round": 20, "enemies": [ { "type": "Armored", "cant": 22 }, { "type": "Pink", "cant": 15 } ], "interval": 410 },
    { "round": 21, "enemies": [ { "type": "Armored", "cant": 18 } ], "interval": 400 },
    { "round": 22, "enemies": [ { "type": "Pink", "cant": 25 }, { "type": "Armored", "cant": 8 } ], "interval": 390 },
    { "round": 23, "enemies": [ { "type": "Armored", "cant": 18 } ], "interval": 380 },
    { "round": 24, "enemies": [ { "type": "Pink", "cant": 30 }, { "type": "Armored", "cant": 10 } ], "interval": 370 },
    { "round": 25, "enemies": [ { "type": "Armored", "cant": 18 }, { "type": "Pink", "cant": 15 }, { "type": "Blue", "cant": 10 } ], "interval": 360 },
    { "round": 26, "enemies": [ { "type": "Pink", "cant": 45 }, { "type": "Armored", "cant": 8 }, { "type": "Yellow", "cant": 20 } ], "interval": 350 },
    { "round": 27, "enemies": [ { "type": "Armored", "cant": 25 }, { "type": "Blue", "cant": 20 }, { "type": "Green", "cant": 20 } ], "interval": 340 },
    { "round": 28, "enemies": [ { "type": "Pink", "cant": 50 }, { "type": "Armored", "cant": 15 }, { "type": "Yellow", "cant": 25 } ], "interval": 330 },
    { "round": 29, "enemies": [ { "type": "Armored", "cant": 30 }, { "type": "Blue", "cant": 25 }, { "type": "Green", "cant": 25 } ], "interval": 320 },
    { "round": 30, "enemies": [ { "type": "Pink", "cant": 55 }, { "type": "Armored", "cant": 20 }, { "type": "Yellow", "cant": 30 } ], "interval": 310 },
    { "round": 31, "enemies": [ { "type": "Armored", "cant": 35 }, { "type": "Blue", "cant": 30 }, { "type": "Green", "cant": 30 } ], "interval": 300 },
    { "round": 32, "enemies": [ { "type": "Pink", "cant": 60 }, { "type": "Armored", "cant": 25 }, { "type": "Yellow", "cant": 35 } ], "interval": 290 },
    { "round": 33, "enemies": [ { "type": "Armored", "cant": 40 }, { "type": "Blue", "cant": 30 }, { "type": "Green", "cant": 30 } ], "interval": 280 },
    { "round": 34, "enemies": [ { "type": "Pink", "cant": 70 }, { "type": "Armored", "cant": 30 }, { "type": "Yellow", "cant": 40 } ], "interval": 275 },
    { "round": 35, "enemies": [ { "type": "Armored", "cant": 40 }, { "type": "Blue", "cant": 35 }, { "type": "Green", "cant": 35 } ], "interval": 270 },
    { "round": 36, "enemies": [ { "type": "Pink", "cant": 80 }, { "type": "Armored", "cant": 35 }, { "type": "Yellow", "cant": 45 } ], "interval": 265 },
    { "round": 37, "enemies": [ { "type": "Armored", "cant": 45 }, { "type": "Blue", "cant": 40 }, { "type": "Green", "cant": 40 } ], "interval": 260 },
    { "round": 38, "enemies": [ { "type": "Pink", "cant": 85 }, { "type": "Armored", "cant": 40 }, { "type": "Yellow", "cant": 50 } ], "interval": 255 },
    { "round": 39, "enemies": [ { "type": "Armored", "cant": 50 }, { "type": "Blue", "cant": 45 }, { "type": "Green", "cant": 45 } ], "interval": 250 },
    { "round": 40, "enemies": [ { "type": "Pink", "cant": 90 }, { "type": "Armored", "cant": 45 }, { "type": "Yellow", "cant": 55 } ], "interval": 245 },
    { "round": 41, "enemies": [ { "type": "Armored", "cant": 40 }, { "type": "Pink", "cant": 70 }, { "type": "Green", "cant": 20 } ], "interval": 240 },
    { "round": 42, "enemies": [ { "type": "Armored", "cant": 45 }, { "type": "Pink", "cant": 75 }, { "type": "Green", "cant": 25 } ], "interval": 238 },
    { "round": 43, "enemies": [ { "type": "Armored", "cant": 50 }, { "type": "Pink", "cant": 80 }, { "type": "Green", "cant": 30 } ], "interval": 235 },
    { "round": 44, "enemies": [ { "type": "Armored", "cant": 55 }, { "type": "Pink", "cant": 85 }, { "type": "Green", "cant": 35 } ], "interval": 233 },
    { "round": 45, "enemies": [ { "type": "Armored", "cant": 60 }, { "type": "Pink", "cant": 90 }, { "type": "Green", "cant": 40 } ], "interval": 230 },
    { "round": 46, "enemies": [ { "type": "Armored", "cant": 65 }, { "type": "Pink", "cant": 95 }, { "type": "Green", "cant": 45 } ], "interval": 228 },
    { "round": 47, "enemies": [ { "type": "Armored", "cant": 70 }, { "type": "Pink", "cant": 100 }, { "type": "Green", "cant": 50 }, { "type": "Yellow", "cant": 20 } ], "interval": 226 },
    { "round": 48, "enemies": [ { "type": "Armored", "cant": 75 }, { "type": "Pink", "cant": 105 }, { "type": "Green", "cant": 55 }, { "type": "Yellow", "cant": 25 } ], "interval": 224 },
    { "round": 49, "enemies": [ { "type": "Armored", "cant": 80 }, { "type": "Pink", "cant": 110 }, { "type": "Green", "cant": 60 }, { "type": "Yellow", "cant": 30 } ], "interval": 222 },
    { "round": 50, "enemies": [ { "type": "Armored", "cant": 90 }, { "type": "Pink", "cant": 120 }, { "type": "Green", "cant": 65 }, { "type": "Yellow", "cant": 35 }, { "type": "Blue", "cant": 40 } ], "interval": 220 }
]