rounds_list = [
    { "round": 1, "enemies": [ { "type": "Red", "cant": 10 } ], "interval": 600 },
    { "round": 2, "enemies": [ { "type": "Red", "cant": 15 } ], "interval": 550 },
    { "round": 3, "enemies": [ { "type": "Blue", "cant": 10 } ], "interval": 500 },
    { "round": 4, "enemies": [ { "type": "Red", "cant": 10 }, { "type": "Blue", "cant": 10 } ], "interval": 500 },
    { "round": 5, "enemies": [ { "type": "Green", "cant": 8 } ], "interval": 450 },
    { "round": 6, "enemies": [ { "type": "Green", "cant": 10 }, { "type": "Blue", "cant": 5 } ], "interval": 450 },
    { "round": 7, "enemies": [ { "type": "Yellow", "cant": 10 } ], "interval": 400 },
    { "round": 8, "enemies": [ { "type": "Yellow", "cant": 12 }, { "type": "Green", "cant": 5 } ], "interval": 400 },
    { "round": 9, "enemies": [ { "type": "Pink", "cant": 10 } ], "interval": 350 },
    { "round": 10, "enemies": [ { "type": "Pink", "cant": 12 }, { "type": "Yellow", "cant": 5 } ], "interval": 350 },
    { "round": 11, "enemies": [ { "type": "Armored", "cant": 5 } ], "interval": 300 },
    { "round": 12, "enemies": [ { "type": "Armored", "cant": 6 }, { "type": "Pink", "cant": 5 } ], "interval": 300 },
    { "round": 13, "enemies": [ { "type": "Armored", "cant": 8 } ], "interval": 280 },
    { "round": 14, "enemies": [ { "type": "Armored", "cant": 10 }, { "type": "Pink", "cant": 5 } ], "interval": 270 },
    { "round": 15, "enemies": [ { "type": "Armored", "cant": 12 } ], "interval": 260 },
    { "round": 16, "enemies": [ { "type": "Pink", "cant": 10 }, { "type": "Yellow", "cant": 10 } ], "interval": 250 },
    { "round": 17, "enemies": [ { "type": "Armored", "cant": 10 }, { "type": "Pink", "cant": 10 } ], "interval": 240 },
    { "round": 18, "enemies": [ { "type": "Armored", "cant": 15 } ], "interval": 230 },
    { "round": 19, "enemies": [ { "type": "Pink", "cant": 15 }, { "type": "Yellow", "cant": 10 } ], "interval": 220 },
    { "round": 20, "enemies": [ { "type": "Armored", "cant": 15 }, { "type": "Pink", "cant": 10 } ], "interval": 210 },
    { "round": 21, "enemies": [ { "type": "Armored", "cant": 18 } ], "interval": 200 },
    { "round": 22, "enemies": [ { "type": "Pink", "cant": 15 }, { "type": "Armored", "cant": 10 } ], "interval": 190 },
    { "round": 23, "enemies": [ { "type": "Armored", "cant": 20 } ], "interval": 180 },
    { "round": 24, "enemies": [ { "type": "Pink", "cant": 20 }, { "type": "Armored", "cant": 10 } ], "interval": 170 },
    { "round": 25, "enemies": [ { "type": "Armored", "cant": 22 } ], "interval": 160 },
    { "round": 26, "enemies": [ { "type": "Pink", "cant": 20 }, { "type": "Armored", "cant": 15 } ], "interval": 150 },
    { "round": 27, "enemies": [ { "type": "Armored", "cant": 25 } ], "interval": 140 },
    { "round": 28, "enemies": [ { "type": "Pink", "cant": 20 }, { "type": "Armored", "cant": 20 } ], "interval": 130 },
    { "round": 29, "enemies": [ { "type": "Armored", "cant": 28 } ], "interval": 120 },
    { "round": 30, "enemies": [ { "type": "Pink", "cant": 20 }, { "type": "Armored", "cant": 25 } ], "interval": 110 },
    { "round": 31, "enemies": [ { "type": "Armored", "cant": 30 } ], "interval": 100 },
    { "round": 32, "enemies": [ { "type": "Pink", "cant": 25 }, { "type": "Armored", "cant": 25 } ], "interval": 90 },
    { "round": 33, "enemies": [ { "type": "Armored", "cant": 32 } ], "interval": 80 },
    { "round": 34, "enemies": [ { "type": "Pink", "cant": 25 }, { "type": "Armored", "cant": 30 } ], "interval": 75 },
    { "round": 35, "enemies": [ { "type": "Armored", "cant": 35 } ], "interval": 70 },
    { "round": 36, "enemies": [ { "type": "Pink", "cant": 25 }, { "type": "Armored", "cant": 32 } ], "interval": 65 },
    { "round": 37, "enemies": [ { "type": "Armored", "cant": 38 } ], "interval": 60 },
    { "round": 38, "enemies": [ { "type": "Pink", "cant": 30 }, { "type": "Armored", "cant": 35 } ], "interval": 55 },
    { "round": 39, "enemies": [ { "type": "Armored", "cant": 40 } ], "interval": 50 },
    { "round": 40, "enemies": [ { "type": "Pink", "cant": 30 }, { "type": "Armored", "cant": 38 } ], "interval": 45 },
    { "round": 41, "enemies": [ { "type": "Armored", "cant": 42 } ], "interval": 40 },
    { "round": 42, "enemies": [ { "type": "Pink", "cant": 35 }, { "type": "Armored", "cant": 40 } ], "interval": 35 },
    { "round": 43, "enemies": [ { "type": "Armored", "cant": 45 } ], "interval": 30 },
    { "round": 44, "enemies": [ { "type": "Pink", "cant": 35 }, { "type": "Armored", "cant": 42 } ], "interval": 28 },
    { "round": 45, "enemies": [ { "type": "Armored", "cant": 48 } ], "interval": 25 },
    { "round": 46, "enemies": [ { "type": "Pink", "cant": 40 }, { "type": "Armored", "cant": 45 } ], "interval": 23 },
    { "round": 47, "enemies": [ { "type": "Armored", "cant": 50 } ], "interval": 20 },
    { "round": 48, "enemies": [ { "type": "Pink", "cant": 40 }, { "type": "Armored", "cant": 48 } ], "interval": 18 },
    { "round": 49, "enemies": [ { "type": "Armored", "cant": 52 } ], "interval": 15 },
    { "round": 50, "enemies": [ { "type": "Armored", "cant": 60 } ], "interval": 12 }
]